### ISSUE TITLE
Multi Value Array/Dictionary

### ISSUE THREAD

**Issue by MaxInterested** [nocode-js/sequential-workflow-editor#31]
Dear Team,

I'd like to express my appreciation for the Workflow Editor. Its user-friendly interface and versatile features made it easy to get started. However, as I delve deeper into its capabilities, I've encountered challenges beyond my current abilities.

I'm currently exploring the Workflow Editor and its capabilities. Specifically, I'm uncertain about how to add a Multi-Value Array or Dictionary to a step. Could you please provide guidance on this matter, or clarify if it's not supported? For example, I'd like to create a dictionary with animals described by Type, Size, and Name.

Thank you for your assistance.

Best regards,
Max 

`export const anyVariablesStepModel = createStepModel<TransitionVariablesStepModel>('animal', 'task', step => {
        step.property('Animal')
            .label('Animal Entry')
            .value(
			[
				{
					createChoiceValueModel({
						choices: ["Dog", "Cat", "Mouse"]
					})
				},
				{
					createNumberValueModel({
						defaultValue: size.Default,
						min: size.Min,
						max: size.Max
					});
				},
				{
					createStringValueModel({
						defaultValue: animalName
					})
				}
        );`

**Comment by b4rtaz** [comment]
Hello @MaxInterested!

Could you draw a mockup what you expect?

Btw: SWE supports a [choice value model](https://nocode-js.com/docs/sequential-workflow-editor/value-models/choice) ([example](https://nocode-js.github.io/sequential-workflow-editor/webpack-app/public/editors.html#choice)).

**Comment by MaxInterested** [comment]
Thanks for the swift response, @b4rtaz . Attached is a mockup drawing, albeit with my apologies in advance for my Paint skills. Your understanding is much appreciated!


![image](https://github.com/nocode-js/sequential-workflow-editor/assets/166233246/1c5b4107-43fc-4a01-8913-67f899d92f8c)

**Comment by MaxInterested** [comment]
Has anything happened in the meantime? Otherwise I'm at a loss as to how to implement it. Thanks in advance

**Comment by b4rtaz** [comment]
@MaxInterested are you considering to buy the pro version? Maybe this is something that we could consider as a pro feature.
