### ISSUE TITLE
Add more support for i18n

### ISSUE THREAD

**Issue by mythsman** [nocode-js/sequential-workflow-editor#37]
It seems that the alert strings in this file (or more) `model/src/validator/variable-name-validator.ts`  have not been converted using context.i18n:
```javascript
export function variableNameValidator(name: string): string | null {
        if (!name) {
                return 'Variable name is required.';
        }
        if (name.length > MAX_LENGTH) {
                return `Variable name must be ${MAX_LENGTH} characters or less.`;
        }
        if (!/^[A-Za-z][a-zA-Z_0-9-]*$/.test(name)) {
                return 'Variable name contains invalid characters.';
        }
        return null;
}
```
Could you please provide support for this?

**Comment by b4rtaz** [comment]
Thanks for reporting, will be fixed soon.

**Comment by b4rtaz** [comment]
Hello @mythsman, please check the [0.13.1](https://github.com/nocode-js/sequential-workflow-editor/releases/tag/v0.13.1) version.

**Comment by b4rtaz** [comment]
Oh, you're right. Thanks! Please check the [0.13.2](https://github.com/nocode-js/sequential-workflow-editor/releases/tag/v0.13.2) version.
