### ISSUE TITLE
Dynamic step stypes

### ISSUE THREAD

**Issue by ggparente95** [nocode-js/sequential-workflow-editor#45]
Hello!

With my team we are currently using the visual workflow designer, with an editor created by us using react & js.
We were evaluating the possibility of migrating to integrate the sequential-workflow-designer, but we have a requirement that I believe does not allow us to do so.
Our step types (or step-models in swd-editor) are defined dynamically in our backend, and today the backend is the one who sends the designer & editor what step types are going to be used.
We couldn't see a way to use the sequential-workflow-designer-editor to achieve this behavior of creating dynamic step-models from the backend information.
Do you have a similar use case perhaps? Or any recommendations to address this case.

Thank you very much in advance.

**Comment by b4rtaz** [comment]
Hello @ggparente95,

yes, you can create steps dynamically. Please check this article: https://nocode-js.com/docs/sequential-workflow-editor/dynamic-model.

Please let me know if this answers your question.
